version: '2'
services:
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./moodle_data:/bitnami/moodle
      - 'moodledata_data:/bitnami/moodle'
    depends_on:
      - mariadb
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8
      - MARIADB_COLLATE=utf8_general_ci
    volumes:
      - ./mariadb_data:/bitnami/mariadb
volumes:
  moodledata_data:
    driver: local
